### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by sryu1** [julianneswinoga/flightgear-python#1]
Is there a documentation for this?

**Comment by sryu1** [comment]
Wait I'm dumb, found it.

**Comment by julianneswinoga** [comment]
Yep no worries! Happens to the best of us haha
Let me know what you think though! Still working on the documentation

**Comment by sryu1** [comment]
I'm reading this and have no idea what any of the functions do https://flightgear-python.readthedocs.io/en/latest/examples.html#simple-fdm-loop 😵😵

**Comment by julianneswinoga** [comment]
All that example does is create a Flight Dynamics Model (FDM) interface with both RX (FG -> python) and TX (python -> FG) connections. The RX connection requires a callback function (function that will be called whenever FG sends data to us).
Then there's an infinite loop where we just increment a variable every 0.01s and send that data to the callback. Since the callback is asynchronous (i.e. it is working as a separate process) we need some mechanism to communicate between the parent process and the child (callback) process which is all an `EventPipe` is
